version: "3.8"
services:
    fullnode:
     network_mode: host
     build:
      context: .
      args:
       - gitUrl
       - fullnodeContainerDir   
       - configFile
     environment:
       - eTicker=${ticker}
     volumes:
       - ./chain.conf:${fullnodeContainerDir}/${configFile}
       - ${fullnodeHostDir}:${fullnodeContainerDir}
     logging:
      driver: "json-file"
      options:
          max-file: "5"
          max-size: "10m"
